// Cypher script generated by docling-graph
// Import this into Neo4j

// --- Create Nodes ---
CREATE (Company_63e47e8fd6843777_0:Company {id: "Company_63e47e8fd6843777", type: "entity", __class__: "Company", name: "Hubei Gedian Humanwell Pharmaceutical Co., Ltd."})
CREATE (Facility_8ef284eefd37dd4d_1:Facility {id: "Facility_8ef284eefd37dd4d", type: "entity", __class__: "Facility", name: "No. 25 Juxian Road, Gedian Economic Development District, Ezhou City, Hubei Province, China"})
CREATE (Person_aaacf0a6a6eaf687_2:Person {id: "Person_aaacf0a6a6eaf687", type: "entity", __class__: "Person", name: "Dr. Hailin Chen", title: "General Manager"})
CREATE (Product_8d74173be869938e_3:Product {id: "Product_8d74173be869938e", type: "entity", __class__: "Product", name: "Drugs"})
CREATE (Observation_9ab7378963881481_4:Observation {id: "Observation_9ab7378963881481", type: "entity", __class__: "Observation", description: "Failure to clean equipment and utensils to prevent contamination or carry-over of material that would alter the integrity of APl-contact surfaces is being compromised which can lead to contamination of your API with particulate matter (e.g., APl particles) or alter the quality of the APl via chemical leachablereactions."})
CREATE (Observation_11708331f034a288_5:Observation {id: "Observation_11708331f034a288", type: "entity", __class__: "Observation", description: "Compatibility between the equipment product contact surface material of construction and the chemical process, specifically the APl chemicals used in the process weakens the APl on the APl surfaces which leads to APl stains/discoloration and APL the APl markings on the APl and lid and replaced the APl gasket sealing the APl lid."})
CREATE (Observation_2ac5f05b667f20ba_6:Observation {id: "Observation_2ac5f05b667f20ba", type: "entity", __class__: "Observation", description: "Your firm manufactures (b)(4) for the U.S. market. During the inspection, our investigator observed numerous scratches the (b)(4) of your (b)(4) vessel. These markings and discolored stains indicate that the integrity of the APl-contact surfaces is being compromised which can lead to contamination of your API with particulate matter (e.g., (b)(4) particles) or alter the quality of the APL via chemical leachablereactions."})
CREATE (Observation_df4bb6bbcc570b65_7:Observation {id: "Observation_df4bb6bbcc570b65", type: "entity", __class__: "Observation", description: "Your response, you state that compatibility between the equipment product contact surface material of construction and the chemical process, specifically the (b)(4) and the (b)(4) process, is insufficient. You state that the (b)(4) chemicals used in the process weakens the (b)(4) on the (b)(4) surfaces which leads to (b)(4) manifested as (b)(4) stains/discoloration and (b)(4) the (b)(4) markings on the (b)(4) and lid and replaced the (b)(4) gasket sealing the (b)(4) lid."})
CREATE (Observation_868654059843d4a9_8:Observation {id: "Observation_868654059843d4a9", type: "entity", __class__: "Observation", description: "Your response also did not evaluate the reactivity of all interior surfaces of the equipment train with your (b)(4) process. Furthermore, your rationalized that there is a risk to product quality risk based on results of release testing using a qualified method."})
CREATE (Observation_d3501c43026ad751_9:Observation {id: "Observation_d3501c43026ad751", type: "entity", __class__: "Observation", description: "The product in that they were additive, absorptive, or reactive. Inadequately maintained manufacturing equipment can lead topotential contamination that could compromise the quality and safety of your APls."})
CREATE (Observation_2591c3010c852d49_10:Observation {id: "Observation_2591c3010c852d49", type: "entity", __class__: "Observation", description: "In response to this letter, provide:"})
CREATE (Observation_8883e8bc9cb245d0_11:Observation {id: "Observation_8883e8bc9cb245d0", type: "entity", __class__: "Observation", description: "- Your corrective action and preventive action (CAPA) plan to implement routine, vigilant operations management oversight of facilities and equipment. This plan should ensure, among other things, prompt detection of maintenance schedules, timely technological upgrades to the equipment/facility infrastructure, and improved systems for ongoing management review."})
CREATE (Observation_9e4c3892add27feb_12:Observation {id: "Observation_9e4c3892add27feb", type: "entity", __class__: "Observation", description: "- discoloration within the (b)(4) vessels introduced as a result of your manufacturing process, including an evaluation last three years."})
CREATE (Observation_544baf7eb1e8bd5a_13:Observation {id: "Observation_544baf7eb1e8bd5a", type: "entity", __class__: "Observation", description: "- A review of all your manufacturing processes to determine whether there is reactivity with all respective product contact surfaces in you equipment."})
CREATE (Observation_6b45503853a366a2_14:Observation {id: "Observation_6b45503853a366a2", type: "entity", __class__: "Observation", description: "- An evaluation of your process and equipment to determine whether changes will be implemented to remove the risk"})
CREATE (Observation_dd30cee8a7abdc8d_15:Observation {id: "Observation_dd30cee8a7abdc8d", type: "entity", __class__: "Observation", description: "Failure to clean equipment and utensils to prevent contamination or carry-over of material that would alter the integrity of APl-contact surfaces is being compromised which can lead to contamination of your API with particulate matter (e.g., APl particles) or alter the quality of the APL via chemical leachablereactions."})
CREATE (Observation_5c76c65c4afe03d3_16:Observation {id: "Observation_5c76c65c4afe03d3", type: "entity", __class__: "Observation", description: "Compatibility between the equipment product contact surface material of construction and the chemical process, specifically the APl chemicals used in the process weakens the APl on the APl surfaces which leads to APl stains/discoloration and APL the APL markings on the APL and lid and replaced the APl gasket sealing the APL lid."})
CREATE (Observation_3d874ba4946deec6_17:Observation {id: "Observation_3d874ba4946deec6", type: "entity", __class__: "Observation", description: "Your firm manufactures (b)(4) for the U.S. market. During the inspection, our investigator observed numerous scratches the (b)(4) product, which are not consistent with the expected surface finish and quality standards."})
CREATE (WarningLetter_a1ac665d8d47c350_18:WarningLetter {id: "WarningLetter_a1ac665d8d47c350", type: "entity", __class__: "WarningLetter", letter_id: "320-26-93", subject: "Warning Letter for Humanwell Pharmaceutical Co., Ltd.", issue_date: "June 3, 2026"})

// --- Create Relationships ---
MATCH (WarningLetter_a1ac665d8d47c350_18), (Company_63e47e8fd6843777_0)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:ISSUED_TO]->(Company_63e47e8fd6843777_0)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Facility_8ef284eefd37dd4d_1)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:INSPECTED_FACILITY]->(Facility_8ef284eefd37dd4d_1)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Person_aaacf0a6a6eaf687_2)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:ADDRESSED_TO]->(Person_aaacf0a6a6eaf687_2)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Product_8d74173be869938e_3)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:INVOLVES_PRODUCT]->(Product_8d74173be869938e_3)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_9ab7378963881481_4)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_9ab7378963881481_4)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_11708331f034a288_5)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_11708331f034a288_5)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_2ac5f05b667f20ba_6)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_2ac5f05b667f20ba_6)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_df4bb6bbcc570b65_7)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_df4bb6bbcc570b65_7)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_868654059843d4a9_8)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_868654059843d4a9_8)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_d3501c43026ad751_9)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_d3501c43026ad751_9)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_2591c3010c852d49_10)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_2591c3010c852d49_10)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_8883e8bc9cb245d0_11)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_8883e8bc9cb245d0_11)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_9e4c3892add27feb_12)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_9e4c3892add27feb_12)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_544baf7eb1e8bd5a_13)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_544baf7eb1e8bd5a_13)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_6b45503853a366a2_14)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_6b45503853a366a2_14)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_dd30cee8a7abdc8d_15)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_dd30cee8a7abdc8d_15)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_5c76c65c4afe03d3_16)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_5c76c65c4afe03d3_16)

MATCH (WarningLetter_a1ac665d8d47c350_18), (Observation_3d874ba4946deec6_17)
CREATE (WarningLetter_a1ac665d8d47c350_18)-[:CONTAINS_OBSERVATION]->(Observation_3d874ba4946deec6_17)

